#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import sys

from vlpp.lib.prepare import Prepare


def get_arguments():

    parser = argparse.ArgumentParser(
            description="""
            """,
            epilog="""
            """)

    parser.add_argument(
            '-p', '--pet_dir',
            required=True,
            help='PET data directory',
            )

    parser.add_argument(
            '-f', '--fs_dir',
            required=True,
            help='Freesurfer subjects directory',
            )

    parser.add_argument(
            '-c', '--csv',
            required=True,
            help='csv file',
            )

    return parser.parse_args()


def main():
    args = get_arguments()
    app = Prepare(args)
    app.run()
    return 0

if __name__ == '__main__':
    sys.exit(main())
