#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import sys

from vlpp.lib.qsub import Qsub


def get_arguments():

    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="""
            Documentation at https://github.com/villeneuvelab/vlpp
            Please report any issues there
            """,
            epilog="""
            "Pas de problème, où est le manuel ?"
            """)

    parser.add_argument(
            '-p', '--pet_dir',
            required=False,
            help='Base directory for all of your PET data',
            )

    parser.add_argument(
            '-f', '--fs_dir',
            required=False,
            help='Base directory for all of your freesurfer data',
            )

    parser.add_argument(
            '-t', '--tsv',
            required=False,
            help='A tsv file describing your participants',
            )

    parser.add_argument(
            '-r', '--rapid',
            required=False, default="yai-974-aa",
            help='Your RAPid number on guillimin',
            )

    parser.add_argument(
            '--qa',
            required=False, action='store_true',
            help='Launch the quality assessment',
            )

    return parser.parse_args()


def main():
    args = get_arguments()
    app = Qsub(args)
    app.run()
    return 0

if __name__ == '__main__':
    sys.exit(main())
