#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import os
import sys

from vlpp.qa import Qa
from vlpp.lib.utils import APP_DIR, load_json


def get_arguments():

    parser = argparse.ArgumentParser(
            description="""
            """,
            epilog="""
            """)

    parser.add_argument(
            '-i', '--in_dir',
            required=True,
            help='vlpp directory output',
            )

    return parser.parse_args()


def main():
    args = get_arguments()

    # Directory
    in_dir = os.path.abspath(args.in_dir)

    # Config
    configFile = os.path.join(APP_DIR, 'config', 'config_qa.json')
    config = load_json(configFile)

    # App
    app = Qa(in_dir, config)
    app.run()
    return 0

if __name__ == '__main__':
    sys.exit(main())
