#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import pandas
import glob
import os
import sys


def get_arguments():

    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="""
            """,
            epilog="""

            Documentation at https://github.com/villeneuvelab/vlpp
            Please report any issues there

            """)

    parser.add_argument(
            '--ref',
            required=False, default="cerebellumCortex",
            help='Reference ROI: [*cerebellumCortex*, wholeCerebellum, whitematter]'
            )

    parser.add_argument(
            '--type',
            required=False, default="suvr",
            help='Data type: [*suvr*, centiloid]'
            )


    return parser.parse_args()


def main():
    args = get_arguments()
    ref = args.ref
    type = args.type
    dataDir = os.getcwd()
    output = os.path.join(dataDir, 'ref-{0}_means_rois_{1}.csv'.format(ref, type))

    subjects = []
    datas = []
    dataFiles = glob.glob('{0}/*/stats/*_ref-{1}*{2}.csv'.format(
        dataDir, ref, type))
    for dataFile in dataFiles:
        subjects.append(dataFile.split("/")[-3])
        datas.append(pandas.read_csv(dataFile))

    df = pandas.concat(datas, keys=subjects)
    meandf = df.get(['StructName', 'mean'])

    rsldf = pandas.DataFrame()
    for struct in meandf['StructName'].xs(subjects[0]):
        tempdf = meandf[meandf['StructName'] == struct]
        tempdf = tempdf.rename(columns={'mean':struct}).reset_index(level=1)
        rsldf[struct] = tempdf[struct]

    rsldf = rsldf.sort_index()
    rsldf.to_csv(output)

if __name__ == '__main__':
    sys.exit(main())

